### ISSUE TITLE
Test `experimental_precondition_script_fails` failed

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#1541]
Observed in: https://github.com/TraceMachina/nativelink/actions/runs/12320044191/job/34399214500

```
  2024-12-13T22:02:14.042758Z ERROR nativelink_worker::local_worker: Error executing action, err: Error { code: Unknown, messages: ["Text file busy (os error 26)", "Could not execute precondition command \"/root/.cache/nativelink/work/c21ba7c4-8ddb-4fea-a34c-3f4f075d3b2f/work/_tmp/e10050f1a12b966d9a81a2b83aedfb79/5730592398591745788/scripts/precondition.sh\""] }
    at nativelink-worker/src/local_worker.rs:332
    in integration_tests_local_worker_test::utils::local_worker_test_utils::local_worker_spawn

test experimental_precondition_script_fails ... FAILED

failures:

---- experimental_precondition_script_fails stdout ----
thread 'experimental_precondition_script_fails' panicked at nativelink-worker/tests/local_worker_test.rs:597:5:
assertion failed: `(left == right)`

Diff < left / right > :
 ExecuteResult {
     worker_id: "foobar",
     instance_name: "foo",
     operation_id: "",
     result: Some(
         InternalError(
             Status {
<                code: 2,
<                message: "Text file busy (os error 26) : Could not execute precondition command \"/root/.cache/nativelink/work/c21ba7c4-8ddb-4fea-a34c-3f4f075d3b2f/work/_tmp/e10050f1a12b966d9a81a2b83aedfb79/5730592398591745788/scripts/precondition.sh\"",
>                code: 8,
>                message: "Preconditions script returned status exit status: 1 - ",
                 details: [],
             },
         ),
     ),
 }

failures:
    experimental_precondition_script_fails
```

**Comment by aaronmondal** [comment]
Observed again in https://github.com/TraceMachina/nativelink/actions/runs/13471494175/job/37645586239

**Comment by aaronmondal** [comment]
Observed again in https://github.com/TraceMachina/nativelink/actions/runs/14382964936/job/40331171522

**Comment by aaronmondal** [comment]
Observed again in https://github.com/TraceMachina/nativelink/actions/runs/14618587392/job/41012511358?pr=1710

**Comment by palfrey** [comment]
Haven't seen for a while
