### ISSUE TITLE
Test `update_with_whole_file_closes_file` is flaky on Windows

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#984]
This is from a recent CI run:

```
2024-06-08T20:44:59.222019Z ERROR nativelink_store::filesystem_store: Failed to delete file, file_path: "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\/12005528146084892232/temp_path/0123456789abcdef000000000000000000010000000000001c00000000000000-10", err: Error { code: Internal, messages: ["background task failed: JoinError::Cancelled(Id(1342))", "Failed to remove file \"C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\/12005528146084892232/temp_path/0123456789abcdef000000000000000000010000000000001c00000000000000-10\""] }
    at nativelink-store\src\filesystem_store.rs:121
    in nativelink_store::filesystem_store::filesystem_delete_file

test update_file_future_drops_before_rename ... ok
test update_with_whole_file_closes_file ... FAILED
test update_with_whole_file_slow_path_when_low_file_descriptors ... ok
test valid_results_after_shutdown_test ... ok

failures:

---- update_with_whole_file_closes_file stdout ----
thread 'update_with_whole_file_closes_file' panicked at nativelink-store\tests\filesystem_store_test.rs:1364:9:
assertion failed: `(left == right)`: Expected 1 permit to be available

Diff < left / right > :
<0
>1
```

**Comment by aaronmondal** [comment]
Appeared again in https://github.com/TraceMachina/nativelink/actions/runs/9587554110/job/26437832708

**Comment by palfrey** [comment]
Haven't seen this recently, closing
